### ISSUE TITLE
Bundling Reflex

### ISSUE THREAD

**Issue by paul-go** [Truebase-com/TruthStack#1]
Bundling of the various Reflex subprojects (currently Reflex Core and Reflex ML) is currently non-existent. There are make.js scripts in each of the root directories, and these should be fleshed out as proper build scripts that handle with typical bundling responsibilities such as:

- Running tests (which are also MIA)
- Stripping of compilation constants
- Minification
- Deployment to npm

**Comment by kaaninel** [comment]
Are we looking for custom solution or a bundler that meets all of these items work too ?

**Comment by paul-go** [comment]
@kaaninel I'm hoping the MakeJS sub-project is going to be able to handle this. MakeJS will need some love, right now it's basically just a giant bucket of functions under a single namespace that make library bundling suck slightly less. Hopefully I can give this some thought in the next few days.

**Comment by kaaninel** [comment]
I was thinking about a cli that searches subdirs for config files and handle stuff with a basic terminal UI. Or maybe a basic web UI with internal http server since we need that anyways. I'm working on some basic task manager kind of system for managing makejs scripts. I could use some thoughts about this how far should I go etc. Is makejs focused only for truebase or is it a general bundler ?
