### ISSUE TITLE
Install.sh not working well with Ubuntu

### ISSUE THREAD

**Issue by kaaninel** [Truebase-com/TruthStack#7]
For installing global npm modules we need sudo permission on ubuntu. Possibly we can move bash script to javascript and check ```os.platform()``` before executing npm install.

**Comment by qti3e** [comment]
You don't actually need `sudo` permission to install global packages if you've installed NPM in a right way from the start. If you try to install a package with sudo once you'll need to install everything with sudo ever since.

And putting a `sudo` in the install.sh breaks things for someone like me who doesn't need `sudo` to install global packages, but on the other hand, if we don't put the sudo in there, nothing **breaks** for you, it just does not work.

So by default, it should run without sudo permission and we should add a flag in `./install.sh` to run `npm install -g`s with sudo.

I'll open a PR to address this issue.
